# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66bf6151b857d97701424e015183c13f22f5fd1b5590801e6acd0a5c9feca69a38fb37aadad495241e994d04425973fbd69884ba665d70bd42f6ac731b14b06a

test:
  secret_key_base: 017c496367dee77c2fe5fe2e5636c2e7ed49090746c0b7a22626c053ffccab6fcf3f144461c7b6f96e582f8163214f769062cfcefb69ac8bc7e0f20e17abc9be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
